services:
  ollama:
    image: ollama/ollama:latest
    container_name: ddev-${DDEV_SITENAME}-ollama
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
volumes:
  ollama: {}
