name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      APP_ENV: test
      APP_DEBUG: 1
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pgsql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Prepare database
        env:
          PGPASSWORD: postgres
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          psql -h localhost -U postgres -c "CREATE DATABASE app_test;" || true
          psql -h localhost -U postgres -d app_test -c "CREATE EXTENSION IF NOT EXISTS vector;"
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/app_test" >> $GITHUB_ENV

      - name: Run PHPUnit
        run: bin/phpunit
